name: Publish create-vilay

on:
  push:
    tags:
      - 'create-vilay_v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
      - run: yarn
      - run: echo ${{ secrets.YARNRC }} | base64 --decode > ~/.yarnrc.yml
      - run: cd packages/create && yarn build && yarn npm publish
